//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamWPF_by_NN_
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPickupPoint
    {
        public int PickupPointID { get; set; }
        public int Postindex { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Home { get; set; }
    }
}
